/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package javaapplication1;

import javax.swing.OverlayLayout;
import java.sql.*;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Locale;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import java.awt.*;

/**
 *
 * @author lenovo
 */
public class AddDocumentUI extends javax.swing.JFrame {
 String selectedType;
 String selectedMemoire="licence";

    /**
     * Creates new form AddDocumentUI
     */
    public AddDocumentUI() {
        initComponents();
            type.setSelectedItem("ouvrage");
        setLocationRelativeTo(null); 


    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnGrpMemoire = new javax.swing.ButtonGroup();
        ajoutDoc = new javax.swing.JLabel();
        cote = new javax.swing.JTextField();
        titre = new javax.swing.JTextField();
        prenom_auteur = new javax.swing.JTextField();
        code_auteur = new javax.swing.JTextField();
        nom_auteur = new javax.swing.JTextField();
        etat = new javax.swing.JComboBox<>();
        type = new javax.swing.JComboBox<>();
        addBtn = new javax.swing.JButton();
        datePicker1 = new com.github.lgooddatepicker.components.DatePicker();
        coteLabel = new javax.swing.JLabel();
        titreLabel = new javax.swing.JLabel();
        dateLabel = new javax.swing.JLabel();
        jLayeredPane2 = new javax.swing.JLayeredPane();
        memoirePanel = new javax.swing.JPanel();
        licenceBtn = new javax.swing.JRadioButton();
        mastereBtn = new javax.swing.JRadioButton();
        doctoratBtn = new javax.swing.JRadioButton();
        ouvragePanel = new javax.swing.JPanel();
        editeur = new javax.swing.JTextField();
        isbn = new javax.swing.JTextField();
        isbnLabel1 = new javax.swing.JLabel();
        editeurLabel1 = new javax.swing.JLabel();
        codeAuteurLabel = new javax.swing.JLabel();
        etatLabel = new javax.swing.JLabel();
        nomAuteurLabel = new javax.swing.JLabel();
        prenomAuteurLabe = new javax.swing.JLabel();
        homeBtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(0, 0, 0));

        ajoutDoc.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        ajoutDoc.setText("Ajouter Document");

        cote.setText("1");

        titre.setText("titre");

        prenom_auteur.setText("prenom_auteur");

        code_auteur.setText("2");

        nom_auteur.setText("nom_auteur");

        etat.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "disponible", "non disponible" }));

        type.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "ouvrage", "memoire" }));
        type.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                typeActionPerformed(evt);
            }
        });

        addBtn.setText("Add");
        addBtn.setBackground(new java.awt.Color(0, 204, 51));
        addBtn.setForeground(new java.awt.Color(255, 255, 255));
        addBtn.setHideActionText(true);
        addBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addBtnActionPerformed(evt);
            }
        });

        coteLabel.setText("Cote");

        titreLabel.setText("Titre");

        dateLabel.setText("Date partution");

        jLayeredPane2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        memoirePanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnGrpMemoire.add(licenceBtn);
        licenceBtn.setSelected(true);
        licenceBtn.setText("Licence");
        licenceBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                licenceBtnActionPerformed(evt);
            }
        });
        memoirePanel.add(licenceBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 10, -1, -1));

        btnGrpMemoire.add(mastereBtn);
        mastereBtn.setText("Mastere");
        mastereBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mastereBtnActionPerformed(evt);
            }
        });
        memoirePanel.add(mastereBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 30, -1, -1));

        btnGrpMemoire.add(doctoratBtn);
        doctoratBtn.setText("Doctorat");
        doctoratBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                doctoratBtnActionPerformed(evt);
            }
        });
        memoirePanel.add(doctoratBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 50, -1, -1));

        jLayeredPane2.add(memoirePanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 220, 100));

        editeur.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editeurActionPerformed(evt);
            }
        });

        isbnLabel1.setText("ISBN");

        editeurLabel1.setText("Editeur");

        javax.swing.GroupLayout ouvragePanelLayout = new javax.swing.GroupLayout(ouvragePanel);
        ouvragePanel.setLayout(ouvragePanelLayout);
        ouvragePanelLayout.setHorizontalGroup(
            ouvragePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ouvragePanelLayout.createSequentialGroup()
                .addGroup(ouvragePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(ouvragePanelLayout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addComponent(editeurLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(isbn, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(ouvragePanelLayout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addComponent(isbnLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(editeur, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(23, 23, 23))
        );
        ouvragePanelLayout.setVerticalGroup(
            ouvragePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ouvragePanelLayout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addGroup(ouvragePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(isbnLabel1)
                    .addComponent(editeur, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(17, 17, 17)
                .addGroup(ouvragePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(editeurLabel1)
                    .addComponent(isbn, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24))
        );

        jLayeredPane2.add(ouvragePanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 330, -1));

        codeAuteurLabel.setText("Code auteur");

        etatLabel.setText("Etat");

        nomAuteurLabel.setText("Nom auteur");

        prenomAuteurLabe.setText("Prenom auteur");

        homeBtn.setBackground(new Color(0, 0, 0, 0));
        homeBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/home icon 50.png"))); // NOI18N
        homeBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                homeBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(75, 75, 75)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(titreLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(coteLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(49, 49, 49))
                    .addComponent(codeAuteurLabel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(dateLabel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(nomAuteurLabel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(etatLabel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(prenomAuteurLabe, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(nom_auteur, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(datePicker1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(titre)
                    .addComponent(etat, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(prenom_auteur)
                    .addComponent(cote)
                    .addComponent(code_auteur))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(146, 146, 146)
                        .addComponent(type, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(81, 81, 81)
                        .addComponent(jLayeredPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 277, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(22, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(addBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(296, 296, 296))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(homeBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(ajoutDoc, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(265, 265, 265))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addComponent(ajoutDoc, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cote, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(coteLabel))
                        .addGap(10, 10, 10)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(titre, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(titreLabel))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(datePicker1, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(dateLabel))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(etat, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(etatLabel))
                        .addGap(8, 8, 8)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(code_auteur, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(codeAuteurLabel))
                        .addGap(28, 28, 28)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(27, 27, 27)
                                .addComponent(nomAuteurLabel))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(7, 7, 7)
                                .addComponent(nom_auteur, javax.swing.GroupLayout.DEFAULT_SIZE, 42, Short.MAX_VALUE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(prenom_auteur, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(prenomAuteurLabe)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(60, 60, 60)
                        .addComponent(type, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLayeredPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(homeBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(addBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(20, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void typeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_typeActionPerformed
         selectedType = (String) type.getSelectedItem();
        if("ouvrage".equals(selectedType)){
            ouvragePanel.setVisible(true);
            memoirePanel.setVisible(false);
        }else{
            memoirePanel.setVisible(true);
            ouvragePanel.setVisible(false);
        }
        
    }//GEN-LAST:event_typeActionPerformed

    private void addBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addBtnActionPerformed
       Connection conn=null;
       PreparedStatement statement=null;
        try {
      conn = DBConnection.getConnection();
      String sql = "INSERT INTO documents (cote, titre, date_parution,etat, code_auteur, nom_auteur, prenom_auteur,type, isbn, editeur, diplome) VALUES (?,?,?,?,?,?,?,?,?,?,?)";
    statement = conn.prepareStatement(sql);
    
    // Gather the data from the text fields
    String coteData = cote.getText();
    String titreData = titre.getText();
    String dateString = datePicker1.getText();  // '1 novembre 2024'
    String code_auteurData = code_auteur.getText();
    String nom_auteurData = nom_auteur.getText();
    String prenom_auteurData = prenom_auteur.getText();
    
    SimpleDateFormat inputFormat = new SimpleDateFormat("d MMMM yyyy", Locale.FRENCH);  
    java.util.Date utilDate = inputFormat.parse(dateString);             
    java.sql.Date sqlDate = new java.sql.Date(utilDate.getTime());  
  

    // Set the common fields
    statement.setString(1, coteData);
    statement.setString(2, titreData);
    statement.setDate(3, sqlDate); 
    statement.setString(4, (String) etat.getSelectedItem());
    statement.setString(5, code_auteurData);
    statement.setString(6, nom_auteurData);
    statement.setString(7, prenom_auteurData);
    statement.setString(8, selectedType);
    
    // Depending on the selected type, set additional fields
    if ("ouvrage".equals(selectedType)) {
        statement.setString(9, isbn.getText()); 
        statement.setString(10, editeur.getText()); 
        statement.setString(11, null); 
    } else {
        // Set diplome for the other case
        statement.setString(9, null); 
        statement.setString(10, null); 
        statement.setString(11, selectedMemoire); 
    }
    
    statement.executeUpdate();
        } catch (SQLException e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(null, "Error adding users: " + e.getMessage());
        } catch (ParseException ex) {
                        JOptionPane.showMessageDialog(null, "Error adding users: " + ex.getMessage());

         Logger.getLogger(AddDocumentUI.class.getName()).log(Level.SEVERE, null, ex);
     }
    }//GEN-LAST:event_addBtnActionPerformed

    private void licenceBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_licenceBtnActionPerformed
        selectedMemoire = licenceBtn.getText();
    }//GEN-LAST:event_licenceBtnActionPerformed

    private void mastereBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mastereBtnActionPerformed
        selectedMemoire = mastereBtn.getText();
    }//GEN-LAST:event_mastereBtnActionPerformed

    private void doctoratBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_doctoratBtnActionPerformed
        selectedMemoire = doctoratBtn.getText();
    }//GEN-LAST:event_doctoratBtnActionPerformed

    private void editeurActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editeurActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_editeurActionPerformed

    private void homeBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_homeBtnActionPerformed
        new AdminDashboardUI().setVisible(true);
        dispose();
    }//GEN-LAST:event_homeBtnActionPerformed

    /**
     * @param args the command line arguments
     */


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addBtn;
    private javax.swing.JLabel ajoutDoc;
    private javax.swing.ButtonGroup btnGrpMemoire;
    private javax.swing.JLabel codeAuteurLabel;
    private javax.swing.JTextField code_auteur;
    private javax.swing.JTextField cote;
    private javax.swing.JLabel coteLabel;
    private javax.swing.JLabel dateLabel;
    private com.github.lgooddatepicker.components.DatePicker datePicker1;
    private javax.swing.JRadioButton doctoratBtn;
    private javax.swing.JTextField editeur;
    private javax.swing.JLabel editeurLabel1;
    private javax.swing.JComboBox<String> etat;
    private javax.swing.JLabel etatLabel;
    private javax.swing.JButton homeBtn;
    private javax.swing.JTextField isbn;
    private javax.swing.JLabel isbnLabel1;
    private javax.swing.JLayeredPane jLayeredPane2;
    private javax.swing.JRadioButton licenceBtn;
    private javax.swing.JRadioButton mastereBtn;
    private javax.swing.JPanel memoirePanel;
    private javax.swing.JLabel nomAuteurLabel;
    private javax.swing.JTextField nom_auteur;
    private javax.swing.JPanel ouvragePanel;
    private javax.swing.JLabel prenomAuteurLabe;
    private javax.swing.JTextField prenom_auteur;
    private javax.swing.JTextField titre;
    private javax.swing.JLabel titreLabel;
    private javax.swing.JComboBox<String> type;
    // End of variables declaration//GEN-END:variables
}
