/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package javaapplication1;
import java.sql.*;
import javax.swing.JOptionPane;
import javax.swing.*;
/**
 *
 * @author lenovo
 */
public class AddPlacardsUI extends JFrame {
        Object[][] tableData=null;
//    
//    public AddPlacardsUI(String previousPage){
//        this.previousPage=previousPage;
//        initComponents();
//        setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);  
//       setLocationRelativeTo(null); 
//       performSearch();
//    }
    /**
     * Creates new form AddAuthorUI
     */
    public AddPlacardsUI() {
        initComponents();
     setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);  
       setLocationRelativeTo(null); 
        performSearch();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        addPlBtn = new javax.swing.JButton();
        title = new javax.swing.JLabel();
        plInput = new javax.swing.JTextField();
        firstNameInput = new javax.swing.JTextField();
        plLabel = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        returnBtn1 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        addAuthorBtn1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        addPlBtn.setBackground(new java.awt.Color(0, 153, 51));
        addPlBtn.setForeground(new java.awt.Color(255, 255, 255));
        addPlBtn.setText("Ajouter Placard");
        addPlBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addPlBtnActionPerformed(evt);
            }
        });

        title.setText("Gérer Placards");

        plLabel.setText("Libelle Placards");

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/add_author (50).png"))); // NOI18N

        returnBtn1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/return_icon.png"))); // NOI18N
        returnBtn1.setAlignmentY(0.0F);
        returnBtn1.setBorderPainted(false);
        returnBtn1.setFocusPainted(false);
        returnBtn1.setFocusable(false);
        returnBtn1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        returnBtn1.setMargin(new java.awt.Insets(0, 0, 0, 0));
        returnBtn1.setRequestFocusEnabled(false);
        returnBtn1.setRolloverEnabled(false);
        returnBtn1.setVerifyInputWhenFocusTarget(false);
        returnBtn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                returnBtn1ActionPerformed(evt);
            }
        });

        jLabel2.setText("Liste des placards");

        addAuthorBtn1.setBackground(new java.awt.Color(0, 153, 51));
        addAuthorBtn1.setForeground(new java.awt.Color(255, 255, 255));
        addAuthorBtn1.setText("Ajouter etagère");
        addAuthorBtn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addAuthorBtn1ActionPerformed(evt);
            }
        });

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(addAuthorBtn1, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(plLabel)
                            .addComponent(plInput, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(firstNameInput, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(addPlBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 89, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(98, 98, 98))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap())))))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(returnBtn1)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(128, 128, 128)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(106, 106, 106)
                        .addComponent(title, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(returnBtn1)
                            .addComponent(title, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(plLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(plInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(addPlBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(firstNameInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabel2)
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(addAuthorBtn1, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(334, 334, 334))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void addPlBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addPlBtnActionPerformed

        if(plInput.getText().isEmpty()){
            JOptionPane.showMessageDialog(null, "Libelle manquant","Alert",JOptionPane.WARNING_MESSAGE);

        }else{
        new Placards((String)plInput.getText()).addPlacard();
        JOptionPane.showMessageDialog(null, "Placard ajouté");
        }
    }//GEN-LAST:event_addPlBtnActionPerformed

    private void returnBtn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_returnBtn1ActionPerformed
//        if("home".equals(this.previousPage)){
//        new AdminDashboardUI().setVisible(true);
//        dispose();
//        }else{
//            dispose();
//        }
    }//GEN-LAST:event_returnBtn1ActionPerformed

    private void addAuthorBtn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addAuthorBtn1ActionPerformed
        performSearch();
    }//GEN-LAST:event_addAuthorBtn1ActionPerformed

    private void performSearch(){
        tableData = new Placards().getPlacards();
                  jTable1.setModel(new javax.swing.table.DefaultTableModel(
                  tableData,
                new String[] {"numero", "Libelle"} 
            ));
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addAuthorBtn1;
    private javax.swing.JButton addPlBtn;
    private javax.swing.JTextField firstNameInput;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField plInput;
    private javax.swing.JLabel plLabel;
    private javax.swing.JButton returnBtn1;
    private javax.swing.JLabel title;
    // End of variables declaration//GEN-END:variables
}
